server:
  port: 8081
spring:
  #  application:
  #    name: MyHome
  datasource:
    url: jdbc:mysql://localhost:3306/lianxi?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.218.131
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  rabbitmq:
    host: 192.168.218.131
    port: 5672
    virtual-host: /
    username: yangyi
    password: 123456
#  cloud:
#    nacos:
#      server-addr: 192.168.153.218:8848
#      discovery:
#        ephemeral: false